# Generated by Django 3.2.8 on 2021-11-08 16:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('arduinoTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='aboutImages')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFormBootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('place_living', models.CharField(max_length=50)),
                ('major_of_study', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(max_length=50)),
                ('why', models.TextField(max_length=5000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=8000)),
                ('edition', models.CharField(max_length=10)),
                ('imageBackground', models.ImageField(upload_to='events')),
                ('imageEvent', models.ImageField(upload_to='eventsImage')),
            ],
        ),
        migrations.CreateModel(
            name='ClubAchivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to='clubAchivemetns')),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('edition', models.CharField(max_length=10)),
                ('imageBackground', models.ImageField(blank=True, upload_to='clubEvents')),
                ('imageEvent', models.ImageField(blank=True, upload_to='clubEventsImages')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('query', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(upload_to='memebers')),
                ('image2', models.ImageField(upload_to='memebers')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='projects')),
                ('owner', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
